### ISSUE TITLE
[chore] 프로젝트 세팅

### ISSUE THREAD

**Issue by seedspirit** [codesquad-masters2024-team6/be-airdnb#1]
## 🔥 Feature Issue
프로젝트에 필요한 디렉토리 구조 설정, 설정 파일 작성합니다

## ✅ TODO
 - [x] 백엔드 디렉토리 설정
 - [x] 스프링부트 application.yaml, build.gradle 설정
 - [x] 프론트엔드 디렉토리 설정
 - [x] sveltekit 앱 초기화
