### ISSUE TITLE
숙소 CRUD를 위한 엔티티 구현

### ISSUE THREAD

**Issue by seedspirit** [codesquad-masters2024-team6/be-airdnb#3]
## 🔥 Feature Issue
숙소 CRUD 구현을 위해 엔티티를 설계합니다.

## ✅ TODO
 - [ ] 숙소 엔티티 설계
 - [ ] 멤버 엔티니 설계
 - [ ] 숙소사진 엔티티 설계
